config/routes.rb
Rails.application.routes.draw do

  resources :games
  resources :ships

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
end

app/models/ship.rb
class Ship < ApplicationRecord
  validates :name, presence: true, length: { minimum: 5 }
  validates_numericality_of :size
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :highscore)
    end
end

app/controllers/ships_controller.rb
class ShipsController < ApplicationController

  def index
    @ships = Ship.all
  end

  def show
    @ship = Ship.find(params[:id])
  end

  def new
    @ship = Ship.new
  end

  def edit
    @ship = Ship.find(params[:id])
  end

  def create
    @ship = Ship.new(ship_params)
    if @ship.save
      redirect_to @ship
    else
      render 'new'
    end
  end

  def update
    @ship = Ship.find(params[:id])

    #you can see why we defined the private
    #ship_params method to keep code DRY
    if @ship.update(ship_params)
      redirect_to @ship
    else
      render 'edit'
    end
  end

  def destroy
    @ship = Ship.find(params[:id])
    @ship.destroy

    redirect_to ships_path
  end

  private

  def ship_params
    params.require(:ship).permit(:name, :size)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/ships_helper.rb
module ShipsHelper
end

app/views/games/_form.html.erb
<%= form_for(game) do |f| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :highscore %>
    <%= f.number_field :highscore %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Highscore</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.name %></td>
        <td><%= game.highscore %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @game.name %>
</p>

<p>
  <strong>Highscore:</strong>
  <%= @game.highscore %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Battlegrounds</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/ships/edit.html.erb
<h1>Editing ship</h1>

<%= form_for :ship, url: ship_path(@ship), method: :patch do |f| %>

    <% if @ship.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@ship.errors.count, "error") %> prohibited
            this ship from being saved:
          </h2>
          <ul>
            <% @ship.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.label :size %><br>
      <%= f.number_field :size %>
    </p>

    <p>
      <%= f.submit %>
    </p>

<% end %>

<%= link_to 'Back', ships_path %>

app/views/ships/index.html.erb
<h1>Listing Ships</h1>
<td><%= link_to 'New', new_ship_path %></td>

<table>
  <tr>
    <th>Name</th>
    <th>Size</th>
    <th colspan="2">Actions</th>
  </tr>
  <% @ships.each do |ship| %>
      <tr>
        <td><%= ship.name %></td>
        <td><%= ship.size %></td>
        <td><%= link_to 'Show', ship_path(ship) %></td>
        <td><%= link_to 'Edit', edit_ship_path(ship) %></td>
      </tr>
  <% end %>
</table>

app/views/ships/new.html.erb
<%= form_for :ship, url: ships_path do |f| %>

    <% if @ship.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@ship.errors.count, "error") %> made so that the ship could not be saved:
          </h2>
          <ul>
            <% @ship.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.label :size %><br>
      <%= f.number_field :size %>
    </p>

    <p>
      <%= f.submit %>
    </p>

<% end %>

<%= link_to 'Back', ships_path %>

app/views/ships/show.html.erb
<p>
  <strong>Size</strong>
  <%= @ship.size %>
</p>
<p>
  <strong>Name</strong>
  <%= @ship.name %>
</p>
<%= link_to 'Edit', edit_ship_path(@ship) %> |
<%= link_to 'Back', ships_path %>